//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class departement_master
    {
        public string Dept_ID { get; set; }
        public string Dept_Desc { get; set; }
        public string c_user_id { get; set; }
        public Nullable<System.DateTime> proc_date { get; set; }
        public string proc_time { get; set; }
        public string client_ip { get; set; }
        public string comp_code { get; set; }
    }
}
