//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class machine_master
    {
        public string loom_type { get; set; }
        public string block { get; set; }
        public string loom_no { get; set; }
        public string loom_model { get; set; }
        public Nullable<decimal> rpm { get; set; }
        public string @operator { get; set; }
        public string proc_by { get; set; }
        public Nullable<int> rec_no { get; set; }
        public string rec_sts { get; set; }
        public Nullable<byte> proc_no { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> proc_date { get; set; }
        public string proc_time { get; set; }
        public string client_ip { get; set; }
        public Nullable<int> seq_no { get; set; }
        public string grey_no { get; set; }
        public Nullable<int> jcm_f { get; set; }
    }
}
