//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_maintenance
    {
        public string mtc_id { get; set; }
        public string mtc_name { get; set; }
        public string user_id { get; set; }
        public string act_rec { get; set; }
        public string client_ip { get; set; }
        public Nullable<System.DateTime> proc_time { get; set; }
    }
}
