//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ms_user_access_button
    {
        public int id { get; set; }
        public string userid { get; set; }
        public string roles { get; set; }
        public string menu { get; set; }
        public string submenu { get; set; }
        public string button { get; set; }
        public string section { get; set; }
    }
}
