//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tr_prev_maintenance
    {
        public decimal dept_id { get; set; }
        public decimal mc_id { get; set; }
        public System.DateTime mtc_schedule { get; set; }
        public string block { get; set; }
        public string loom_no { get; set; }
        public System.DateTime mtc_start { get; set; }
        public Nullable<System.DateTime> mtc_finish { get; set; }
        public string mtc_id { get; set; }
        public string mtc_action_id { get; set; }
        public string pic_mtc { get; set; }
        public string user_id { get; set; }
        public string rec_sts { get; set; }
        public Nullable<int> proc_no { get; set; }
        public string client_ip { get; set; }
        public Nullable<System.DateTime> proc_time { get; set; }
    }
}
