//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Machine_Trouble
    {
        public decimal dept_id { get; set; }
        public string Department { get; set; }
        public decimal mc_id { get; set; }
        public string Machine { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
    }
}
