//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Maintenance_Type_for_Maintenance_Action
    {
        public string Trouble_Type { get; set; }
        public string trouble_id { get; set; }
        public string trouble_name { get; set; }
    }
}
