//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_SAP_OITM
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string nama_sparepart { get; set; }
        public string no_catalog { get; set; }
    }
}
