//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_user_ism_maintenance
    {
        public string ID { get; set; }
        public string Fullname { get; set; }
        public string departement { get; set; }
        public string section { get; set; }
        public string roles { get; set; }
    }
}
