//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_preventivemaintenance_history
    {
        public string mtcSchedule { get; set; }
        public string mtcNo { get; set; }
        public string startMtc { get; set; }
        public string finishMtc { get; set; }
        public string mtcDuration { get; set; }
        public string dept_name { get; set; }
        public string mc_name { get; set; }
        public string mtc_name { get; set; }
        public string mtc_action_name { get; set; }
        public string Fullname { get; set; }
        public System.DateTime mtc_schedule { get; set; }
        public string block { get; set; }
        public string loom_no { get; set; }
        public System.DateTime mtc_start { get; set; }
        public Nullable<System.DateTime> mtc_finish { get; set; }
        public decimal dept_id { get; set; }
        public decimal mc_id { get; set; }
        public string mtc_id { get; set; }
        public string mtc_action_id { get; set; }
        public string pic_mtc { get; set; }
        public Nullable<int> proc_no { get; set; }
        public Nullable<System.DateTime> mtcSpace { get; set; }
    }
}
