//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_grey_insp_defect_master
    {
        public string defect_code { get; set; }
        public string defect_name { get; set; }
        public string defect_alias { get; set; }
        public string defect_type { get; set; }
        public int defect_category { get; set; }
        public string rec_sts { get; set; }
        public byte proc_no { get; set; }
        public string user_id { get; set; }
        public System.DateTime proc_date { get; set; }
        public string client_ip { get; set; }
    }
}
