//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISM_MAINTENANCE.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WvMaintenanceEntities : DbContext
    {
        public WvMaintenanceEntities()
            : base("name=WvMaintenanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ms_dept> ms_dept { get; set; }
        public virtual DbSet<ms_machine_type> ms_machine_type { get; set; }
        public virtual DbSet<ms_maintenance> ms_maintenance { get; set; }
        public virtual DbSet<ms_maintenance_action> ms_maintenance_action { get; set; }
        public virtual DbSet<wv_grey_insp_defect_master> wv_grey_insp_defect_master { get; set; }
        public virtual DbSet<ms_machine_trouble> ms_machine_trouble { get; set; }
        public virtual DbSet<sysuser_app> sysuser_app { get; set; }
        public virtual DbSet<v_Machine_Trouble> v_Machine_Trouble { get; set; }
        public virtual DbSet<v_Machine_Type> v_Machine_Type { get; set; }
        public virtual DbSet<departement_master> departement_master { get; set; }
        public virtual DbSet<v_Maintenance_Action> v_Maintenance_Action { get; set; }
        public virtual DbSet<v_Maintenance_Type_for_Maintenance_Action> v_Maintenance_Type_for_Maintenance_Action { get; set; }
        public virtual DbSet<v_Maintenance_Activity> v_Maintenance_Activity { get; set; }
        public virtual DbSet<v_Machine_Master_AJL> v_Machine_Master_AJL { get; set; }
        public virtual DbSet<v_Mtc_Action_For_Mtc_Result> v_Mtc_Action_For_Mtc_Result { get; set; }
        public virtual DbSet<v_Details2> v_Details2 { get; set; }
        public virtual DbSet<tr_maintenance_action> tr_maintenance_action { get; set; }
        public virtual DbSet<tr_maintenance_sparepart> tr_maintenance_sparepart { get; set; }
        public virtual DbSet<tr_shift_leader_note> tr_shift_leader_note { get; set; }
        public virtual DbSet<tr_shift_leader_note_detail> tr_shift_leader_note_detail { get; set; }
        public virtual DbSet<v_Shift_Leader_Header> v_Shift_Leader_Header { get; set; }
        public virtual DbSet<tr_maintenance> tr_maintenance { get; set; }
        public virtual DbSet<v_Shift_Leader> v_Shift_Leader { get; set; }
        public virtual DbSet<v_MaintenanceHistory> v_MaintenanceHistory { get; set; }
        public virtual DbSet<machine_master> machine_master { get; set; }
        public virtual DbSet<v_MaintenanceSparepart> v_MaintenanceSparepart { get; set; }
        public virtual DbSet<v_MaintenanceActionShiftLeaderNotes> v_MaintenanceActionShiftLeaderNotes { get; set; }
        public virtual DbSet<vw_preventivemaintenance_history> vw_preventivemaintenance_history { get; set; }
        public virtual DbSet<vw_preventivemaintenance_sparepart> vw_preventivemaintenance_sparepart { get; set; }
        public virtual DbSet<tr_prev_maintenance> tr_prev_maintenance { get; set; }
        public virtual DbSet<v_SAP_OITM> v_SAP_OITM { get; set; }
        public virtual DbSet<v_SAP_OITM_PRICE> v_SAP_OITM_PRICE { get; set; }
        public virtual DbSet<tr_prev_maintenance_sparepart> tr_prev_maintenance_sparepart { get; set; }
        public virtual DbSet<vw_ms_maintenance_action_machine> vw_ms_maintenance_action_machine { get; set; }
        public virtual DbSet<vw_ms_maintenance_action_preventive> vw_ms_maintenance_action_preventive { get; set; }
        public virtual DbSet<vw_ms_maintenance_action_quality> vw_ms_maintenance_action_quality { get; set; }
        public virtual DbSet<v_MaintenanceActionforModal> v_MaintenanceActionforModal { get; set; }
        public virtual DbSet<ms_user_access_menu> ms_user_access_menu { get; set; }
        public virtual DbSet<ms_machine_trouble_hist> ms_machine_trouble_hist { get; set; }
        public virtual DbSet<tr_maintenance_action_hist> tr_maintenance_action_hist { get; set; }
        public virtual DbSet<tr_maintenance_hist> tr_maintenance_hist { get; set; }
        public virtual DbSet<tr_maintenance_sparepart_hist> tr_maintenance_sparepart_hist { get; set; }
        public virtual DbSet<tr_shift_leader_note_detail_hist> tr_shift_leader_note_detail_hist { get; set; }
        public virtual DbSet<tr_shift_leader_note_hist> tr_shift_leader_note_hist { get; set; }
        public virtual DbSet<ms_user_access_button> ms_user_access_button { get; set; }
        public virtual DbSet<v_user_ism_maintenance> v_user_ism_maintenance { get; set; }
    
        public virtual ObjectResult<autonum_preventivemaintenance_Result> autonum_preventivemaintenance(string type)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<autonum_preventivemaintenance_Result>("autonum_preventivemaintenance", typeParameter);
        }
    
        public virtual ObjectResult<view_preventivemaintenance_Result> view_preventivemaintenance(string type, string find)
        {
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var findParameter = find != null ?
                new ObjectParameter("find", find) :
                new ObjectParameter("find", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<view_preventivemaintenance_Result>("view_preventivemaintenance", typeParameter, findParameter);
        }
    }
}
